import { IBusiness, ICertification, IJob, IPortfolioItem, IProfessional } from "./store";

// Sample construction professionals
export const dummyProfessionals: IProfessional[] = [
  {
    id: "p1",
    name: "Alex Johnson",
    email: "alex.johnson@example.com",
    phone: "+1234567890",
    bio: "Master electrician with 12+ years of experience in residential and commercial electrical installations, maintenance, and repairs.",
    skills: ["Electrical Installation", "Wiring Systems", "Circuit Maintenance", "HVAC Electrical", "Commercial Lighting"],
    certifications: [
      {
        id: "c1",
        name: "Master Electrician License",
        issuer: "State Board of Electrical Contractors",
        date: "2020-05-15",
        validUntil: "2025-05-15",
        verified: true,
        documentUrl: "/certs/electrician-license.pdf",
      },
      {
        id: "c2",
        name: "OSHA 30-Hour Construction Safety",
        issuer: "Occupational Safety and Health Administration",
        date: "2021-08-20",
        verified: true,
      },
    ],
    portfolio: [
      {
        id: "port1",
        title: "Downtown Office Complex Rewiring",
        description: "Complete electrical system upgrade for a 15-story commercial building including energy-efficient lighting installation.",
        imageUrl: "/portfolio/electrical-work.jpg",
        altText: "Commercial electrical installation with neatly organized wiring",
        tags: ["Commercial", "Electrical Upgrade", "Lighting", "Energy Efficiency"],
        date: "2023-01-15",
      },
      {
        id: "port2",
        title: "Residential Smart Home Integration",
        description: "Installed comprehensive smart home electrical systems for a new construction luxury home development.",
        imageUrl: "/portfolio/smarthome.jpg",
        altText: "Smart home electrical panel and control system",
        tags: ["Residential", "Smart Home", "Automation", "New Construction"],
        date: "2022-11-05",
      },
    ],
    availability: true,
    location: "San Francisco, CA",
    profileComplete: 95,
    verified: true,
  },
  {
    id: "p2",
    name: "Samantha Lee",
    email: "samantha.lee@example.com",
    bio: "Experienced plumbing contractor specializing in commercial plumbing systems and water conservation solutions.",
    skills: ["Commercial Plumbing", "Water Heating Systems", "Pipe Installation", "Leak Detection", "Water Conservation"],
    certifications: [
      {
        id: "c3",
        name: "Master Plumber License",
        issuer: "State Plumbing Board",
        date: "2022-02-10",
        verified: true,
      },
    ],
    portfolio: [
      {
        id: "port3",
        title: "Hospital Plumbing System Installation",
        description: "Designed and installed medical-grade plumbing systems for a new hospital wing, meeting strict health code requirements.",
        imageUrl: "/portfolio/hospital-plumbing.jpg",
        altText: "Medical facility plumbing installation",
        tags: ["Medical Facility", "Health Code Compliant", "Commercial"],
        date: "2023-02-20",
      },
    ],
    availability: false,
    location: "New York, NY",
    profileComplete: 85,
    verified: true,
  },
  {
    id: "p3",
    name: "Michael Chen",
    email: "michael.chen@example.com",
    phone: "+1987654321",
    bio: "HVAC technician with expertise in commercial and industrial heating, ventilation, and air conditioning systems.",
    skills: ["HVAC Installation", "Commercial Refrigeration", "Ventilation Systems", "Climate Control", "Energy Efficiency"],
    certifications: [
      {
        id: "c4",
        name: "NATE HVAC Certification",
        issuer: "North American Technician Excellence",
        date: "2022-09-30",
        validUntil: "2025-09-30",
        verified: true,
      },
    ],
    portfolio: [
      {
        id: "port4",
        title: "Industrial Warehouse HVAC System",
        description: "Installed energy-efficient HVAC system for a 50,000 sq ft distribution center with specialized cooling zones.",
        imageUrl: "/portfolio/hvac-industrial.jpg",
        altText: "Industrial HVAC installation",
        tags: ["Industrial", "HVAC", "Energy Efficient", "Zone Control"],
        date: "2023-03-15",
      },
    ],
    availability: true,
    location: "Austin, TX",
    profileComplete: 90,
    verified: false,
  },
];

// Sample construction businesses
export const dummyBusinesses: IBusiness[] = [
  {
    id: "b1",
    name: "BuildRight Construction",
    email: "contact@buildright.example",
    phone: "+1122334455",
    description: "General contractor specializing in commercial and residential construction projects.",
    industry: ["Construction", "General Contracting", "Commercial Development"],
    location: "San Francisco, CA",
    verified: true,
  },
  {
    id: "b2",
    name: "Modern Renovations Ltd",
    email: "hello@modernrenovations.example",
    description: "Renovation specialists focusing on luxury residential and historic building restorations.",
    industry: ["Renovations", "Residential Construction", "Historic Restoration"],
    location: "New York, NY",
    verified: true,
  },
  {
    id: "b3",
    name: "GreenBuild Developers",
    email: "info@greenbuild.example",
    phone: "+1555666777",
    description: "Sustainable construction company focusing on eco-friendly building practices and materials.",
    industry: ["Green Construction", "Sustainable Development", "LEED Projects"],
    location: "Seattle, WA",
    verified: false,
  },
];

// Sample construction jobs
export const dummyJobs: IJob[] = [
  {
    id: "j1",
    title: "Senior Electrician",
    description: "Looking for an experienced electrician to join our team for a 6-month commercial building project including complete electrical system installation.",
    businessId: "b1",
    businessName: "BuildRight Construction",
    location: "San Francisco, CA",
    skills: ["Electrical Installation", "Commercial Lighting", "Building Codes", "Blueprint Reading"],
    datePosted: "2023-04-01",
    deadline: "2023-04-30",
    status: "open",
  },
  {
    id: "j2",
    title: "Plumbing Contractor for Luxury Development",
    description: "Seeking a skilled plumbing contractor to install complete systems in a new luxury condominium development.",
    businessId: "b2",
    businessName: "Modern Renovations Ltd",
    location: "New York, NY (On-site)",
    skills: ["Residential Plumbing", "Luxury Fixtures", "Water Systems", "Code Compliance"],
    datePosted: "2023-03-28",
    deadline: "2023-04-20",
    status: "open",
  },
  {
    id: "j3",
    title: "HVAC Specialist - Commercial Systems",
    description: "Looking for an HVAC technician with commercial experience to install and commission systems in a new office building.",
    businessId: "b3",
    businessName: "GreenBuild Developers",
    location: "Seattle, WA",
    skills: ["HVAC Installation", "Commercial Systems", "Energy Efficiency", "System Commissioning"],
    datePosted: "2023-03-25",
    deadline: "2023-04-25",
    status: "open",
  },
  {
    id: "j4",
    title: "Finish Carpenter (Contract)",
    description: "3-month contract for a skilled finish carpenter to complete interior woodwork on a historic building restoration.",
    businessId: "b2",
    businessName: "Modern Renovations Ltd",
    location: "Brooklyn, NY",
    skills: ["Finish Carpentry", "Historical Restoration", "Custom Woodwork", "Detail Oriented"],
    datePosted: "2023-03-20",
    status: "closed",
  },
  {
    id: "j5",
    title: "Solar Panel Installation Technician",
    description: "Help our clients transition to renewable energy with professional solar panel installations on residential properties.",
    businessId: "b3",
    businessName: "GreenBuild Developers",
    location: "Portland, OR",
    skills: ["Solar Installation", "Roofing Experience", "Electrical Knowledge", "Renewable Energy"],
    datePosted: "2023-04-02",
    status: "draft",
  },
];

// Construction Skills list for filters and selects
export const skillsList = [
  "Electrical Installation", "Commercial Lighting", "Wiring Systems", "Electrical Maintenance", "Circuit Troubleshooting",
  "Residential Plumbing", "Commercial Plumbing", "Pipe Fitting", "Water Heater Installation", "Drain Cleaning",
  "HVAC Installation", "Air Conditioning", "Heating Systems", "Ventilation", "Refrigeration",
  "Carpentry", "Framing", "Finish Carpentry", "Cabinetry", "Woodworking",
  "Masonry", "Concrete Work", "Bricklaying", "Stone Setting", "Foundation Work",
  "Drywall Installation", "Plastering", "Taping", "Finishing", "Texturing",
  "Painting", "Staining", "Refinishing", "Wall Coverings", "Color Matching",
  "Roofing", "Metal Roofing", "Shingle Installation", "Flat Roofing", "Waterproofing",
  "Flooring Installation", "Tile Setting", "Hardwood Flooring", "Laminate Installation", "Carpet Installation",
  "Welding", "Metal Fabrication", "Steel Framing", "Structural Steel", "Ornamental Metal",
  "Blueprint Reading", "Construction Planning", "Project Management", "Site Supervision", "Cost Estimation",
  "Heavy Equipment Operation", "Crane Operation", "Excavation", "Grading", "Demolition",
  "Green Building", "LEED Knowledge", "Sustainable Construction", "Energy Efficiency", "Solar Installation",
  "Building Codes", "Safety Compliance", "OSHA Standards", "Permit Processing", "Inspections"
];

// Locations list
export const locationsList = [
  "San Francisco, CA",
  "New York, NY",
  "Austin, TX",
  "Seattle, WA",
  "Boston, MA",
  "Chicago, IL",
  "Los Angeles, CA",
  "Denver, CO",
  "Miami, FL",
  "Atlanta, GA",
  "Dallas, TX",
  "Portland, OR",
  "Washington, DC",
  "Remote"
];

// Industries list
export const industriesList = [
  "Technology",
  "Software Development",
  "Design",
  "Marketing",
  "Finance",
  "Healthcare",
  "Education",
  "E-commerce",
  "Media",
  "Entertainment",
  "Consulting",
  "Real Estate",
  "Manufacturing",
  "Retail",
  "Transportation",
  "Energy",
  "Hospitality",
  "Non-profit"
]; 